version: '3.8'

services:
  lm-studio:
    image: lmstudio/lmstudio:latest
    container_name: lm-studio
    ports:
      - "1234:1234"  # LM Studio API port
    volumes:
      - ./lm-studio-models:/app/models  # Mount models directory
      - ./lm-studio-config:/app/config  # Mount config directory
      - ./lm-studio-data:/app/data      # Mount data directory
    environment:
      - LM_STUDIO_API_PORT=1234
      - LM_STUDIO_HOST=0.0.0.0
      - LM_STUDIO_MODELS_PATH=/app/models
      - LM_STUDIO_CONFIG_PATH=/app/config
      - LM_STUDIO_DATA_PATH=/app/data
    restart: unless-stopped
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1234/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (if needed)
  redis:
    image: redis:alpine
    container_name: ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - ai-network
    command: redis-server --appendonly yes

volumes:
  redis-data:

networks:
  ai-network:
    driver: bridge
